-- vim: ts=4 sw=4 et
-- Post-decode
--
-- Fetch->Decode->Load->PostDecode->...
--
-- Performs variant and environment decoding:
--   - Determine current XLEN context
--   - sign extension
--   - Modify opFlags etc. based on processor feature settings
--   - Assign opFlags for word width (BHWD) by current XLEN if none set

